using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace UIControllerGenerator.Generator;

[Generator]
public class UIControllerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax c && c.BaseList != null,
                static (syntaxContext, _) => syntaxContext.Node as ClassDeclarationSyntax)
            .Where(static node => node != null).Select(static (node, _) => node!).Collect();
        context.RegisterSourceOutput(candidates,
            (sourceContext, nodes) => GenerateUIControllerExecute(sourceContext, nodes));
    }

    #region GenerateUIController

    private void GenerateUIControllerExecute(SourceProductionContext context, ImmutableArray<ClassDeclarationSyntax> candidates)
    {
        var types = new List<(string className, string namespaceName)>();
        foreach (var classNode in candidates)
        {
            var namespaceNode = classNode.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
            if (namespaceNode == null || !Definition.TargetNameSpaces.Contains(namespaceNode.Name.ToString())) continue;
            if (classNode.BaseList == null || !classNode.BaseList.Types.Any(t => t.Type.ToString().Equals(Definition.InterfaceName))) continue;
            types.Add((classNode.Identifier.Text, namespaceNode.Name.ToString()));
        }
        if (types.Count > 0) context.AddSource("UIController_Gen.g.cs", GenerateUIControllerCode(types));
    }

    private string GenerateUIControllerCode(List<(string className, string namespaceName)> controllerTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// \tThis code was generated by the source generator.");
        sb.AppendLine("// \tChanges to this file may cause incorrect behavior.");
        sb.AppendLine("// \twill be lost if the code is regenerated.");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine();

        foreach (var usingNameSpace in Definition.UsingNameSpace)
        {
            sb.AppendLine($"using {usingNameSpace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {Definition.NameSpace}");
        {
            sb.AppendLine("{");
            sb.AppendLine($"\tpublic sealed partial class {Definition.TargetClassName}");
            {
                sb.AppendLine("\t{");

                // 生成字段
                sb.AppendLine("\t\t#region UIController");
                sb.AppendLine();
                sb.AppendLine("\t\tprivate List<IUIController> m_uiControllers = new List<IUIController>();");
                sb.AppendLine();

                // 生成 RegisterAllController 方法
                sb.AppendLine("\t\tpartial void RegisterAllController()");
                {
                    sb.AppendLine("\t\t{");
                    foreach (var (className, _) in controllerTypes)
                    {
                        sb.AppendLine($"\t\t\tAddUIController<{className}>();");
                    }
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();

                // 生成 AddUIController 方法
                sb.AppendLine("\t\tprivate void AddUIController<T>() where T : IUIController, new()");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tfor (int i = 0; i < m_uiControllers.Count; i++)");
                    {
                        sb.AppendLine("\t\t\t{");
                        sb.AppendLine("\t\t\t\tvar type = m_uiControllers[i].GetType();");
                        sb.AppendLine("\t\t\t\tif (type == typeof(T))");
                        {
                            sb.AppendLine("\t\t\t\t{");
                            sb.AppendLine("\t\t\t\t\tDLogger.Fatal(\"repeat controller type: {0}\", typeof(T).Name);");
                            sb.AppendLine("\t\t\t\t\treturn;");
                            sb.AppendLine("\t\t\t\t}");
                        }
                        sb.AppendLine("\t\t\t}");
                    }
                    sb.AppendLine();
                    sb.AppendLine("\t\t\tvar controller = new T();");
                    sb.AppendLine("\t\t\tm_uiControllers.Add(controller);");
                    sb.AppendLine();
                    sb.AppendLine("\t\t\tcontroller.RegUIMessage();");
                    sb.AppendLine("\t\t}");
                }

                sb.AppendLine();
                sb.AppendLine("\t\t#endregion");
                sb.AppendLine("\t}");
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// 获取匹配的类声明语法（实现了 IUIController 接口的类）
    /// </summary>
    private IEnumerable<ClassDeclarationSyntax> GetMatchClasses(SyntaxNode root)
        => root.DescendantNodes().OfType<ClassDeclarationSyntax>()
            .Where(c => c.BaseList != null &&
                       c.BaseList.Types.Any(t => t.Type.ToString().Equals(Definition.InterfaceName)));

    /// <summary>
    /// 获取类所在的命名空间
    /// </summary>
    private string GetNamespace(ClassDeclarationSyntax classNode)
    {
        var namespaceNode = classNode.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
        return namespaceNode?.Name.ToString() ?? string.Empty;
    }

    #endregion
}
