using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DataCenterModuleGenerator.Generator;

[Generator]
public class DataCenterModuleGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax c && c.BaseList != null,
                static (syntaxContext, _) => syntaxContext.Node as ClassDeclarationSyntax)
            .Where(static node => node != null).Select(static (node, _) => node!).Collect();
        context.RegisterSourceOutput(candidates,
            (sourceContext, nodes) => GenerateDataCenterModuleExecute(sourceContext, nodes));
    }

    #region GenerateDataCenterModule

    private void GenerateDataCenterModuleExecute(SourceProductionContext context, ImmutableArray<ClassDeclarationSyntax> candidates)
    {
        var types = new List<(string className, string namespaceName)>();
        foreach (var classNode in candidates)
        {
            var namespaceNode = classNode.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
            if (namespaceNode == null || !Definition.TargetNameSpaces.Contains(namespaceNode.Name.ToString())) continue;
            if (classNode.BaseList == null || !classNode.BaseList.Types.Any(t => t.Type.ToString().StartsWith(Definition.BaseClassName))) continue;
            types.Add((classNode.Identifier.Text, namespaceNode.Name.ToString()));
        }
        if (types.Count > 0) context.AddSource("DataCenterModule_Gen.g.cs", GenerateDataCenterModuleCode(types));
    }

    private string GenerateDataCenterModuleCode(List<(string className, string namespaceName)> moduleTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// \tThis code was generated by the source generator.");
        sb.AppendLine("// \tChanges to this file may cause incorrect behavior.");
        sb.AppendLine("// \twill be lost if the code is regenerated.");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("//----------------------------------------------------------");
        sb.AppendLine();

        sb.AppendLine($"namespace {Definition.NameSpace}");
        {
            sb.AppendLine("{");
            sb.AppendLine($"\tpublic sealed partial class {Definition.TargetClassName}");
            {
                sb.AppendLine("\t{");
                sb.AppendLine();
                sb.AppendLine("\t\tpartial void InitModule()");
                {
                    sb.AppendLine("\t\t{");
                    foreach (var (className, _) in moduleTypes)
                    {
                        sb.AppendLine($"\t\t\tRegisterModule({className}.Instance);");
                    }
                    sb.AppendLine("\t\t}");
                }
                sb.AppendLine();

                sb.AppendLine("\t\t/// <summary>");
                sb.AppendLine("\t\t/// 注册数据中心模块。");
                sb.AppendLine("\t\t/// </summary>");
                sb.AppendLine("\t\t/// <param name=\"module\">要注册的模块</param>");
                sb.AppendLine("\t\tpublic void RegisterModule(IDataCenterModule module)");
                {
                    sb.AppendLine("\t\t{");
                    sb.AppendLine("\t\t\tif (m_dataCenterModuleList.Contains(module))");
                    sb.AppendLine("\t\t\t{");
                    sb.AppendLine("\t\t\t\treturn;");
                    sb.AppendLine("\t\t\t}");
                    sb.AppendLine("\t\t\tmodule.OnInit();");
                    sb.AppendLine("\t\t\tm_dataCenterModuleList.Add(module);");
                    sb.AppendLine("\t\t}");
                }
                sb.AppendLine("\t}");
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// 获取匹配的类声明语法（继承了 DataCenterModule 的类）
    /// </summary>
    private IEnumerable<ClassDeclarationSyntax> GetMatchClasses(SyntaxNode root)
        => root.DescendantNodes().OfType<ClassDeclarationSyntax>()
            .Where(c => c.BaseList != null &&
                       c.BaseList.Types.Any(t => t.Type.ToString().StartsWith(Definition.BaseClassName)));

    /// <summary>
    /// 获取类所在的命名空间
    /// </summary>
    private string GetNamespace(ClassDeclarationSyntax classNode)
    {
        var namespaceNode = classNode.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
        return namespaceNode?.Name.ToString() ?? string.Empty;
    }

    #endregion
}